namespace MRecipeStructure.Classes.MRecipeStructure
{
	public enum TileStyle
	{
		INTERNAL_CLOCKWISE_SPIRAL,
		INTERNAL_COUNTER_CLOCKWISE_SPIRAL,
		EXTERNAL_CLOCKWISE_SPIRAL,
		EXTERNAL_COUNTER_CLOCKWISE_SPIRAL,
		RASTER,
		RASTER_REVERSED,
		SEPERTINE,
		SEPERTINE_REVERSED
	}
}
